package de.hszg.datenpannen.model.dataloss;

/**
 *
 * Aufteilungen der Kosten
 */
public enum CostDistribution {

    INVESTIGATIONS_AND_FORENSICS,
    LOST_CUSTOMER_BUSINESS,
    AUDIT_AND_CONSULTING_SERVICES,
    OUTBOUND_CONTACT_COSTS,
    LEGAL_SERVICES_COMPLIANCE,
    CUSTOMER_ACQUISITION_COST,
    INBOUND_CONTACT_COSTS,
    LEGAL_SERVICES_DEFENSE,
    FREE_OR_DISCOUNTED_SERVICES,
    IDENTITY_PROTECTION_SERVICES,
    PUBLIC_RELATIONS_COMMUNICATIONS;
}
