package de.hszg.datenpannen.model.virus;

public enum Sector {

    FINANCIAL_SERVICES,
    UTILITIES_AND_ENERGY,
    PHARMACEUTICAL,
    TECHNOLOGY,
    PUBLIC_SECTOR,
    EDUCATION_AND_RESEARCH,
    INDUSTRIAL,
    TRANSPORTATION,
    SERVICES,
    HOSPITALITY,
    CONSUMER_PRODUCTS,
    AUTOMOTIVE,
    MEDIA,
    RETAIL;  
    
}
