package de.hszg.datenpannen.model.virus;

public enum SecurityGovernanceActivity {

    EXTENSIVE_USE_OF_SECURITY_METRICS,
    SUBSTANTIAL_TRAINING_AND_AWARENESS_ACTIVITIES,
    EMPLOYMENT_OF_CERTIFIED_EXPERT_SECURITY_PERSONNEL,
    FORMATION_OF_A_SENIOR_LEVEL_SECURITY_COUNCIL,
    APPOINTMENT_OF_A_HIGH_LEVEL_SECURITY_LEADER,
    ADEQUACY_OF_BUDGETED_RESOURCES,
    CERTIFICATION_AGAINST_INDUSTRY_LEADING_STANDARDS,
    NONE;
}
